package com.codepattern.analysis

import com.codepattern.models.*
import com.codepattern.patterns.PatternMatcher
import com.codepattern.report.ReportGenerator
import com.codepattern.scanner.ScannedProject
import java.io.File

/**
 * Generates .codepattern.md — a file that AI coding agents read automatically.
 *
 * When this file exists in a repo, AI agents (Claude, Cursor, Copilot, etc.)
 * see it as part of their context and follow the architecture rules.
 *
 * This is what makes the plugin go viral:
 * 1. Dev runs `--init` → generates .codepattern.md
 * 2. .codepattern.md lives in the repo (committed to git)
 * 3. Every AI agent that touches the repo reads it
 * 4. AI follows the rules → cleaner code → dev tells other devs
 *
 * Also generates:
 * - Pre-commit hook script
 * - GitHub Action workflow
 * - Architecture health badge URL
 */
object AIRuleGenerator {

    /**
     * Generate .codepattern.md from current project analysis.
     * This file is designed to be read by AI agents as coding rules.
     */
    fun generateAgentRules(
        project: ScannedProject,
        basePath: String,
        patterns: List<PatternSpec>,
        violations: List<Violation>
    ): String {
        val matcher = PatternMatcher()
        val healthScore = ReportGenerator.computeHealthScore(violations, project.files.size)

        val sb = StringBuilder()
        sb.appendLine("# Architecture Rules — Code Pattern Analyzer")
        sb.appendLine()
        sb.appendLine("<!-- This file is auto-generated by Code Pattern Analyzer (https://github.com/codepattern) -->")
        sb.appendLine("<!-- AI agents: READ THIS FILE before writing any code in this project -->")
        sb.appendLine("<!-- Last updated: ${java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ISO_LOCAL_DATE_TIME)} -->")
        sb.appendLine("<!-- Health Score: $healthScore/100 -->")
        sb.appendLine()

        // Architecture pattern
        sb.appendLine("## Architecture")
        sb.appendLine()
        for (pattern in patterns) {
            sb.appendLine("This project follows **${pattern.name}** architecture.")
            sb.appendLine()
            if (pattern.description.isNotBlank()) {
                sb.appendLine("> ${pattern.description}")
                sb.appendLine()
            }

            if (pattern.layers.isNotEmpty()) {
                sb.appendLine("### Layer Structure")
                sb.appendLine()
                sb.appendLine("| Layer | Description | Allowed Dependencies |")
                sb.appendLine("|-------|-------------|---------------------|")
                for (layer in pattern.layers) {
                    val deps = if (layer.allowedDependencies.isEmpty()) "None (innermost)" else layer.allowedDependencies.joinToString(", ")
                    sb.appendLine("| **${layer.name}** | ${layer.description} | $deps |")
                }
                sb.appendLine()

                sb.appendLine("### File Placement Rules")
                sb.appendLine()
                for (layer in pattern.layers) {
                    if (layer.filePatterns.isNotEmpty()) {
                        sb.appendLine("- **${layer.name}**: Place files matching `${layer.filePatterns.joinToString("`, `")}`")
                    }
                    if (layer.namingConventions.isNotEmpty()) {
                        sb.appendLine("  - Naming: classes should match `${layer.namingConventions.joinToString("`, `")}`")
                    }
                }
                sb.appendLine()
            }

            // Rules as directives
            if (pattern.rules.isNotEmpty()) {
                sb.appendLine("### Rules")
                sb.appendLine()
                for (rule in pattern.rules) {
                    val severity = when (rule.severity) {
                        ViolationSeverity.ERROR -> "MUST"
                        ViolationSeverity.WARNING -> "SHOULD"
                        ViolationSeverity.INFO -> "MAY"
                    }
                    sb.appendLine("- **$severity**: ${rule.description} *(${rule.name})*")
                }
                sb.appendLine()
            }
        }

        // Complexity rules
        sb.appendLine("## Complexity Limits")
        sb.appendLine()
        sb.appendLine("- **Cyclomatic complexity** per method: max 10 (WARNING), max 20 (ERROR)")
        sb.appendLine("- **Cognitive complexity** per method: max 15")
        sb.appendLine("- **Method length**: max 50 lines")
        sb.appendLine("- **Parameter count**: max 5 parameters per method")
        sb.appendLine("- **File length**: max 500 lines per file")
        sb.appendLine()

        // Memory rules
        sb.appendLine("## Memory & Resource Rules")
        sb.appendLine()
        sb.appendLine("- **MUST** close all resources (streams, connections, readers) using try-with-resources or `.use {}`")
        sb.appendLine("- **MUST NOT** use `finalize()` — use `AutoCloseable` instead")
        sb.appendLine("- **MUST** call `ThreadLocal.remove()` in finally blocks")
        sb.appendLine("- **SHOULD NOT** concatenate strings in loops — use `StringBuilder`")
        sb.appendLine("- **SHOULD NOT** allocate objects inside hot loops")
        sb.appendLine("- **MUST** add eviction policy to caches (max size + TTL)")
        sb.appendLine("- **SHOULD** unregister listeners in `dispose()`/`onDestroy()`/`close()`")
        sb.appendLine()

        // Thread safety rules
        sb.appendLine("## Thread Safety Rules")
        sb.appendLine()
        sb.appendLine("- **MUST** use `@Volatile` or `AtomicReference` for shared mutable state")
        sb.appendLine("- **MUST NOT** nest synchronized blocks (deadlock risk)")
        sb.appendLine("- **MUST NOT** call blocking operations inside `suspend` functions — use `withContext(Dispatchers.IO)`")
        sb.appendLine("- **SHOULD** use `Executors.newFixedThreadPool()` instead of raw `Thread().start()`")
        sb.appendLine("- **SHOULD** use `ConcurrentHashMap.computeIfAbsent()` instead of `containsKey()` + `put()`")
        sb.appendLine("- **MUST** synchronize on `private val` objects, never on mutable fields")
        sb.appendLine()

        // Security rules
        sb.appendLine("## Security Rules (OWASP)")
        sb.appendLine()
        sb.appendLine("- **MUST NOT** concatenate user input into SQL queries — use parameterized queries (CWE-89)")
        sb.appendLine("- **MUST NOT** hardcode passwords, API keys, tokens, or secrets — use environment variables (CWE-798)")
        sb.appendLine("- **MUST NOT** use `Runtime.exec()` or `ProcessBuilder` with user input (CWE-78)")
        sb.appendLine("- **MUST NOT** use MD5/SHA1 for security purposes — use SHA-256+ or bcrypt (CWE-327)")
        sb.appendLine("- **MUST** sanitize user input before rendering in HTML (CWE-79)")
        sb.appendLine("- **MUST** validate and sanitize file paths to prevent path traversal (CWE-22)")
        sb.appendLine("- **MUST** disable external entity processing in XML parsers (CWE-611)")
        sb.appendLine("- **SHOULD** use `SecureRandom` instead of `java.util.Random` for security-sensitive operations")
        sb.appendLine("- **SHOULD** add rate limiting to public API endpoints")
        sb.appendLine()

        // Dead code rules
        sb.appendLine("## Code Hygiene")
        sb.appendLine()
        sb.appendLine("- **SHOULD** remove unused imports")
        sb.appendLine("- **MUST NOT** leave empty catch blocks — handle or log the exception")
        sb.appendLine("- **SHOULD NOT** commit commented-out code — use version control")
        sb.appendLine("- **SHOULD** remove unreachable code after return/throw statements")
        sb.appendLine("- **SHOULD NOT** duplicate code blocks — extract shared logic into methods")
        sb.appendLine()

        // Naming conventions
        sb.appendLine("## Naming Conventions")
        sb.appendLine()

        // Detect language from project
        val languages = project.files.groupBy { it.language }.mapValues { it.value.size }
            .toList().sortedByDescending { it.second }
        val primaryLang = languages.firstOrNull()?.first ?: "kotlin"

        when (primaryLang) {
            "kotlin", "java" -> {
                sb.appendLine("- Classes: `PascalCase`")
                sb.appendLine("- Functions/methods: `camelCase`")
                sb.appendLine("- Constants: `UPPER_SNAKE_CASE`")
                sb.appendLine("- Packages: `lowercase.dotted`")
            }
            "python" -> {
                sb.appendLine("- Classes: `PascalCase`")
                sb.appendLine("- Functions/variables: `snake_case`")
                sb.appendLine("- Constants: `UPPER_SNAKE_CASE`")
                sb.appendLine("- Modules: `snake_case`")
            }
            "typescript", "javascript" -> {
                sb.appendLine("- Classes/Components: `PascalCase`")
                sb.appendLine("- Functions/variables: `camelCase`")
                sb.appendLine("- Constants: `UPPER_SNAKE_CASE`")
                sb.appendLine("- Files: `kebab-case` or `PascalCase` for components")
            }
            "go" -> {
                sb.appendLine("- Exported: `PascalCase`")
                sb.appendLine("- Unexported: `camelCase`")
                sb.appendLine("- Acronyms: `URL`, `HTTP` (all caps)")
            }
            "rust" -> {
                sb.appendLine("- Types/Traits: `PascalCase`")
                sb.appendLine("- Functions/variables: `snake_case`")
                sb.appendLine("- Constants: `UPPER_SNAKE_CASE`")
            }
            else -> {
                sb.appendLine("- Follow the language's standard naming conventions")
            }
        }
        sb.appendLine()

        // Current violations (so AI knows what to fix)
        if (violations.isNotEmpty()) {
            val errors = violations.filter { it.severity == ViolationSeverity.ERROR }
            if (errors.isNotEmpty()) {
                sb.appendLine("## Current Violations to Fix")
                sb.appendLine()
                sb.appendLine("These violations exist and should be fixed when touching these files:")
                sb.appendLine()
                for (v in errors.take(20)) {
                    sb.appendLine("- `${v.filePath}:${v.lineNumber}` — ${v.message}")
                }
                if (errors.size > 20) {
                    sb.appendLine("- ... and ${errors.size - 20} more errors")
                }
                sb.appendLine()
            }
        }

        // Verification command
        sb.appendLine("## Verification")
        sb.appendLine()
        sb.appendLine("Run before committing:")
        sb.appendLine("```bash")
        sb.appendLine("java -jar code-pattern-analyzer.jar --review .")
        sb.appendLine("```")
        sb.appendLine()
        sb.appendLine("The review must return **PASS** or **WARN** (not FAIL) before code is merged.")

        return sb.toString()
    }

    /**
     * Generate a pre-commit hook script.
     */
    fun generatePreCommitHook(): String {
        return """#!/bin/sh
# Code Pattern Analyzer — pre-commit hook
# Auto-generated. Install: cp this to .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit

echo "Running Code Pattern Analyzer..."

# Check if the JAR exists
JAR_PATH="${'$'}{CODEPATTERN_JAR:-code-pattern-analyzer.jar}"
if [ ! -f "${'$'}JAR_PATH" ]; then
    # Try common locations
    for path in ./code-pattern-analyzer.jar ./tools/code-pattern-analyzer.jar /usr/local/bin/code-pattern-analyzer.jar; do
        if [ -f "${'$'}path" ]; then
            JAR_PATH="${'$'}path"
            break
        fi
    done
fi

if [ ! -f "${'$'}JAR_PATH" ]; then
    echo "Warning: code-pattern-analyzer.jar not found. Skipping analysis."
    echo "Set CODEPATTERN_JAR env var or place the JAR in your project root."
    exit 0
fi

# Run incremental review (only changed files)
RESULT=${'$'}(java -jar "${'$'}JAR_PATH" --review --incremental --format json . 2>/dev/null)
VERDICT=${'$'}(echo "${'$'}RESULT" | grep -o '"verdict": "[^"]*"' | head -1 | cut -d'"' -f4)
SCORE=${'$'}(echo "${'$'}RESULT" | grep -o '"score": [0-9]*' | head -1 | awk '{print ${'$'}2}')

if [ "${'$'}VERDICT" = "FAIL" ]; then
    echo ""
    echo "╔══════════════════════════════════════════╗"
    echo "║     CODE REVIEW GATE — BLOCKED           ║"
    echo "║     Score: ${'$'}SCORE/100 — FAIL              ║"
    echo "╚══════════════════════════════════════════╝"
    echo ""
    echo "Fix the violations before committing."
    echo "Run: java -jar ${'$'}JAR_PATH --review ."
    echo ""
    exit 1
elif [ "${'$'}VERDICT" = "WARN" ]; then
    echo "Code Pattern Analyzer: WARN (Score: ${'$'}SCORE/100) — proceeding with warnings."
else
    echo "Code Pattern Analyzer: PASS (Score: ${'$'}SCORE/100)"
fi

exit 0
"""
    }

    /**
     * Generate GitHub Action workflow.
     */
    fun generateGitHubAction(): String {
        return """name: Architecture Review
on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master]

jobs:
  architecture-review:
    runs-on: ubuntu-latest
    name: Code Pattern Analysis
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Code Pattern Analyzer
        run: |
          curl -sL https://github.com/codepattern/code-pattern-analyzer/releases/latest/download/code-pattern-analyzer.jar -o code-pattern-analyzer.jar

      - name: Run Architecture Review
        id: review
        run: |
          java -jar code-pattern-analyzer.jar --review --format json --output review.json .
          VERDICT=${'$'}(cat review.json | python3 -c "import sys,json; print(json.load(sys.stdin)['verdict'])")
          SCORE=${'$'}(cat review.json | python3 -c "import sys,json; print(json.load(sys.stdin)['score'])")
          echo "verdict=${'$'}VERDICT" >> ${'$'}GITHUB_OUTPUT
          echo "score=${'$'}SCORE" >> ${'$'}GITHUB_OUTPUT

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = JSON.parse(fs.readFileSync('review.json', 'utf8'));
            const icon = review.verdict === 'PASS' ? '✅' : review.verdict === 'WARN' ? '⚠️' : '❌';

            let body = `## ${'$'}{icon} Architecture Review: ${'$'}{review.verdict} (${'$'}{review.score}/100)\n\n`;

            for (const cat of review.categories) {
              const catIcon = cat.verdict === 'PASS' ? '✅' : cat.verdict === 'WARN' ? '⚠️' : '❌';
              body += `${'$'}{catIcon} **${'$'}{cat.category}**: ${'$'}{cat.summary}\n`;
            }

            if (review.blockers.length > 0) {
              body += `\n### Blockers\n`;
              for (const b of review.blockers.slice(0, 10)) {
                body += `- ${'$'}{b}\n`;
              }
            }

            body += `\n---\n*Generated by [Code Pattern Analyzer](https://github.com/codepattern)*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Fail on FAIL verdict
        if: steps.review.outputs.verdict == 'FAIL'
        run: |
          echo "Architecture review FAILED. Fix violations before merging."
          exit 1
"""
    }

    /**
     * Generate a diff-only analysis report.
     * Only checks files that changed in the current git diff.
     * Perfect for AI agents: "check only what I just wrote."
     */
    fun analyzeDiff(
        projectPath: String,
        patterns: List<PatternSpec>,
        fromRef: String = "HEAD"
    ): CodeReviewGate.ReviewResult {
        val changes = IncrementalScanner.getChangedFilesSinceLastCommit(projectPath)
        if (changes.isFullScan || changes.allChanged.isEmpty()) {
            return CodeReviewGate.review(projectPath, patterns)
        }

        val scanner = com.codepattern.standalone.StandaloneScanner()
        val project = scanner.scanFiles(projectPath, changes.allChanged)

        return CodeReviewGate.reviewProject(project, projectPath, patterns)
    }

    /**
     * Generate the --init command output: creates all config files.
     */
    fun initProject(
        projectPath: String,
        patterns: List<PatternSpec>
    ): List<Pair<String, String>> {
        val scanner = com.codepattern.standalone.StandaloneScanner()
        val project = scanner.scan(projectPath)
        val matcher = PatternMatcher()

        // Auto-detect best pattern
        val selectedPatterns = if (patterns.isNotEmpty()) patterns else {
            autoDetectPatterns(project)
        }

        val violations = mutableListOf<Violation>()
        for (pattern in selectedPatterns) {
            violations += matcher.analyze(project, pattern)
        }

        val files = mutableListOf<Pair<String, String>>()

        // 1. .codepattern.md — AI agent rules
        files += Pair(
            ".codepattern.md",
            generateAgentRules(project, projectPath, selectedPatterns, violations)
        )

        // 2. Pre-commit hook
        files += Pair(
            ".codepattern/hooks/pre-commit",
            generatePreCommitHook()
        )

        // 3. GitHub Action
        files += Pair(
            ".github/workflows/architecture-review.yml",
            generateGitHubAction()
        )

        // 4. .codepattern.yml config
        val patternNames = selectedPatterns.joinToString(", ") { "\"${it.name.lowercase().replace(" ", "-")}\"" }
        files += Pair(
            ".codepattern.yml",
            """# Code Pattern Analyzer configuration
patterns: [$patternNames]

# Fitness thresholds for CI/CD
fitness:
  min_health_score: 70
  max_errors: 0
  max_warnings: 20
  max_cyclomatic_complexity: 15
  max_method_lines: 60

# Excluded directories
exclude:
  - node_modules
  - build
  - dist
  - .git
"""
        )

        return files
    }

    private fun autoDetectPatterns(project: ScannedProject): List<PatternSpec> {
        val loader = com.codepattern.patterns.PatternLoader()
        val allPatterns = loader.loadBuiltInPatterns()

        val topDirs = project.files.map { it.relativePath.split("/").firstOrNull() ?: "" }
            .filter { it.isNotBlank() }.map { it.lowercase() }.toSet()

        val detected = mutableListOf<PatternSpec>()

        // Always include SOLID + Code Quality
        allPatterns.find { it.name.contains("SOLID", ignoreCase = true) }?.let { detected += it }
        allPatterns.find { it.name.contains("Code Quality", ignoreCase = true) }?.let { detected += it }

        // Detect architecture
        if (topDirs.any { it in setOf("controllers", "views", "models", "controller", "view", "model") }) {
            allPatterns.find { it.name == "MVC" }?.let { detected += it }
        }
        if (topDirs.any { it in setOf("domain", "usecases", "use_cases", "entities", "infrastructure") }) {
            allPatterns.find { it.name.contains("Clean") }?.let { detected += it }
        }
        if (topDirs.any { it in setOf("ports", "adapters") }) {
            allPatterns.find { it.name.contains("Hexagonal") }?.let { detected += it }
        }
        if (topDirs.any { it in setOf("commands", "queries") }) {
            allPatterns.find { it.name.contains("CQRS") }?.let { detected += it }
        }

        return detected.ifEmpty { allPatterns.take(2) } // Fallback: SOLID + first pattern
    }
}
